name: btop-desktop
adopt-info: btop
summary: BTop Desktop
description: |
 Modern and colorful command line resource monitor that shows usage and stats
 btop is a modern and colorful command line resource monitor that shows
 usage and stats for processor, memory, disks, network and processes.
 btop features:
  - Easy to use, with a game inspired menu system.
  - Full mouse support, all buttons with a highlighted key is clickable
  and mouse scroll works in process list and menu boxes.
  - Fast and responsive UI with UP, DOWN keys process selection.
  - Function for showing detailed stats for selected process.
  - Ability to filter processes.
  - Easy switching between sorting options.
  - Tree view of processes.
  - Send any signal to selected process.
  - UI menu for changing all config file options.
  - Auto scaling graph for network usage.
  - Shows IO activity and speeds for disks
  - Battery meter
  - Selectable symbols for the graphs
  - Custom presets
  - And more...
license: Apache-2.0
base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy/libpxbackend-1.0.so:
    symlink: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy/libpxbackend-1.0.so

apps:
  btop-desktop:
    command: usr/bin/btop-desktop
    extensions: [ gnome ]
    desktop: usr/share/applications/btop-desktop.desktop
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    plugs:
      - mount-observe
      - process-control
      - system-observe
      - hardware-observe
      - network
      - network-observe
      - removable-media

parts:
  btop:
    source: https://github.com/aristocratos/btop
    source-type: git
    plugin: make
    make-parameters:
      - CXX=g++-13
      - PREFIX=/usr
      - STATIC=true
      - ADDFLAGS="-D SNAPPED"
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"

  vte:
    source: https://gitlab.gnome.org/GNOME/vte.git
    source-tag: '0.70.5'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Dgir=false
      - -Da11y=false
      - -Dicu=false
      - -Ddocs=false
      - -Dglade=false
      - -Dgnutls=true
      - -Dfribidi=false
      - -Dgtk3=false
      - -Dgtk4=true
      - -D_systemd=false
      - -Dvapi=false
    override-pull: |
      craftctl default
      sed -i 's#error=format#format#' meson.build
    prime:
      - usr/lib/*/libvte*gtk4.so.*

  btop-desktop:
    after: [ vte ]
    plugin: meson
    source: https://github.com/kenvandine/btop-desktop.git
    source-type: git
    meson-parameters:
      - --prefix=/usr
    override-build: |
      craftctl default
      sed -i.bak -e 's|btop.svg$|${SNAP}/usr/share/icons/hicolor/scalable/apps/btop.svg|g' $CRAFT_PART_INSTALL/usr/share/applications/btop-desktop.desktop
    prime:
      - usr/bin/btop-desktop
      - usr/share/applications/btop-desktop.desktop
      - usr/share/icons

  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup:
    after: [btop, btop-desktop]
    plugin: nil
    build-snaps: [core24, gtk-common-themes, gnome-46-2404]
    override-prime: |
      set -eux
      for snap in "core24" "gtk-common-themes" "gnome-46-2404"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done
